# Vulnerability Analysis Module Configuration

paths:
  input_data: data/processed/
  output_data: data/vulnerability_analysis/
  logs: logs/vulnerability_analysis/

component_profiling:
  model_type: random_forest  # Options: random_forest, gradient_boosting
  test_size: 0.2
  epochs: 100
  batch_size: 64
  learning_rate: 0.001
  hidden_layers: [64, 32]  # For neural network models
  feature_selection: true
  cross_validation: true
  cv_folds: 5

environmental_threat:
  threat_types: 
    - high_temperature
    - low_temperature
    - high_wind
    - precipitation
  threshold_percentiles:
    high_temperature: 95
    low_temperature: 5
    high_wind: 95
    precipitation: 95
  calculate_cumulative: true
  time_lag_analysis: true
  max_lag_days: 7
  seasonal_adjustment: true
  location_based_thresholds: true

correlation_analysis:
  correlation_methods: 
    - pearson
    - spearman
  control_variables: 
    - season
    - time_of_day
  component_grouping: true
  significance_level: 0.05
  generate_visualizations: true
  feature_clustering: true
  cluster_method: hierarchical
  temporal_analysis:
    enabled: true
    min_window_days: 30
    max_window_days: 365

logging:
  level: INFO
  file: logs/vulnerability_analysis/module.log
  rotation: 5MB  # Rotate log file when it reaches this size
  backups: 3     # Keep this many backup log files
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

visualization:
  style: seaborn-whitegrid
  figure_size: [12, 8]
  dpi: 300
  interactive: false  # Set to true for interactive visualizations
  color_palette: viridis
  save_formats: 
    - png
    - svg
